### ISSUE TITLE
Corriger et ajouter noms à liste de valeurs "people"

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-data#1]
[Originally posted on GoogleCode (id 307) on 2012-09-11]

Amy:

Je ne sais pourquoi je ne suis pas autorisé à modifier les listes de valeurs. Il faut dire que je ne me logge pas à chaque fois, la bd se rappelant de ma dernière ouverture, mais...

Quoiqu'il en soit, svp ajouter à la liste &quot;people&quot;:
Bouchard, Denis; Brouillet, Luc

J'en ai rencontré d'autres en faisant des corrections que je n'ai pu ajouter mais ne me rappelle plus des noms...

merci

Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-09-11 12:49Z]

ajouter le nouveau "nom" à "déterminé par" au tableau Determination, ID 2650

(note pour se rappeler où aller ajouter le nom manquant) L

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-09-11 12:56Z]

ajouter à 2671, 2866, 2869

**Comment by herbier** [comment]
[Originally posted on GoogleCode on 2012-09-11 16:57Z by amy.vandal.13]

Le nom Bouchard, Denis; Brouillet, Luc a été ajouté pour les ID 2650, 2671, ainsi que 2686 et 2695 puisque la note D. Bouchard, Luc Brouillet, 1992, MT. se trouvait aussi pour ces spécimens

Je n'ai pas retiré les notes pour les spécimens 2650, 2671, 2686 et 2695, est-ce correcte?

il y a déjà un déterminateur dans 2866 et 2869 (Claude, Ginette; Houle, Gilles). Vérifier si ces deux derniers spécimens sont vraiment à changer.
