### ISSUE TITLE
Faute d'orthographe

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-data#100]
[Originally posted on GoogleCode (id 407) on 2013-02-14 by cl.bouchard6]

ID TAXON 8155

??? faute d'orthographe pour Luzula mutiflora (Ehrhart) Lejeune
1 seul spécimen ID 34720 est entré avec l'erreur

Claire B.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-02-20 15:02Z]

comme une fiche avec l'orthographie correcte existe, j'ai supprimé ce nom erroné, après avoir corrigé entrée

Merci
Luc
