### ISSUE TITLE
indet on the original label

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-data#102]
[Originally posted on GoogleCode (id 54) on 2012-02-21 by irbv]

<b>(This is the template to report a data issue. For another issue, change the</b>
<b>template above.)</b>

<b>What data issue did you discover in the database?</b>

In rare cases where no identification was made by the collector in the original identification field on the label, what should we put in the determination field??? The revision that appears on the annotation label should be in the 2nd determinator field.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-02-21 21:31Z]

Il faut v�rifier avec la bd originale (sur DropBox) ou sur le sp�cimen pour
v�rifier que les donn�es sont bien l� o� elles le doivent dans d�termination
originale et dans les d�terminations subs�quentes. Il sembl ey avoir eu des
m�langes.

Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-03-02 16:56Z]

le terme à utiliser est: unknown
