### ISSUE TITLE
Herbier du Collège Notre-Dame

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-data#103]
[Originally posted on GoogleCode (id 80) on 2012-02-29 by irbv]

<b>(This is the template to report a data issue. For another issue, change the</b>
<b>template above.)</b>

<b>What data issue did you discover in the database?</b>

We must insert a new Herbarium in the historical section of the database: «Collège Notre-Dame, Côte-des-Neiges, Montréal». A lot of specimens in MT come from this institution.

Stu

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-03-07 20:00Z]

Déjà dans la bd: 317

J'ai aussi noté un doublon pour Sir Wilfred Grenfell College Herbarium, Memorial University : 189 et 191

Devrais-je en éliminer un?

Luc
