### ISSUE TITLE
Carex à re-déterminer MT177134

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-data#11]
[Originally posted on GoogleCode (id 1375) on 2014-10-23]

MT177134
CArex communis var. wheeleri = C. austrina fide PL
ms ce taxon n'est pas au Qc

Le spécimen doit être re-déterminé
Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-10-23 12:25Z]

Même dét MT177467

**Comment by geoffreyhall** [comment]
[Originally posted on GoogleCode on 2014-10-23 17:59Z]

nouvelle dét. effectuée et ajoutée
