### ISSUE TITLE
New taxon

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-data#116]
[Originally posted on GoogleCode (id 446) on 2013-03-04 by francois.lambert.3]

Scientific name:  Carex aquatilis var. plumbeophila

ID of the specimen(s): 184069

Your name: François Lambert

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-03-05 15:29Z]

le nom a été entré ds la bd

Geoff: il faut ajouter le nom du "District of Columbia" dans la liste des Province/Etat: en effet, cette localité n'est pas au Colorado tel qu'entré originalement (enlevé de la bd car erroné)

**Comment by geoffreyhall** [comment]
[Originally posted on GoogleCode on 2013-03-05 16:18Z]

184070 :  Peter a choisi "Washington, D.C." au lieu de District of Columbia, donc je ne change rien pour l'instant.  François est maintenant au courant de cette composante de la géographie américaine et la fiche est complétée

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-03-05 16:20Z]

Quand j'ai regardé la liste, je n'ai pas trouvé District of Columbia. ESt-ce que cela se trouve parmi les choix?

Luc

**Comment by geoffreyhall** [comment]
[Originally posted on GoogleCode on 2013-03-05 20:20Z]

District of Columbia ajouté à la liste d'entités subnationales et substitué sur les enregistrements passés pour Washington, D.C.
