### ISSUE TITLE
determination likely wrong for MT176532

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-data#14]
[Originally posted on GoogleCode (id 1384) on 2014-10-24]

Localité est W. Va. et la det. que tu as faite est C. deflexa var. boottii, qui est seulement à l'W des Rocheuses - valider ta det.

Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-10-24 18:24Z]

Vérifier aussi si spécimen 177967 est à MT - marqué unknown présentement et cela n'a aucun sens
L

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-10-24 18:24Z]

Vérifier aussi si spécimen 177967 est à MT - marqué unknown présentement et cela n'a aucun sens
L

**Comment by geoffreyhall** [comment]
[Originally posted on GoogleCode on 2014-10-24 19:04Z]

MT-176532 a été re-déterminé à Carex albicans var. albicans (rubrique corrigée); MT-177967 est à MT (rubrique corrigée)
