### ISSUE TITLE
Bry. Eur. vs Bruch

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-data#175]
Lucie

Comment se fait-il que partout ds la bd originale, Bruch est remplacé par Bry. Eur. dans les autorités, ce qui n'a aucun sens? Je passais mon temps à ajouter ce qui me semblait être une source mais qui ne l'est pas - c'est une erreur d'entrée ou de remplacement global

Luc

**Comment by Luciefortin** [comment]
Pas une erreur d'entrée
