### ISSUE TITLE
Plusieurs espèces ms une seule fiche

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-data#181]
139975
139979
tous deux L-435 : 139980 ; enveloppe séparée de Amblystegium riparium longifolium = 139981? ce dernier pourrait aussi bien être var. que f. longifolium puisque Dupret ne le dit pas - y a-t-il des indications?

139983 : polycarpon et intermedius? mais les deux = Drepanocladus aduncus - si c'est le cas, ne pas ajouter à moins d'une claire annotation - annotation finale sera le nom acc que j'ai ajouté

139984: Etait mélangé à H. giganteum ?
139985 : id

**Comment by brouille** [comment]
139987 : Drepanocladus subpilig. falcat. - autre sp? [subpiliger existe?]
139988 : spécimen de D. capillifolius récolté à date antérieure : séparer?
139995
139998 : voir remarque à det 1
139999
140000 : vérifié Best : annotation stet ou pas?
il y avait du v. polycarpon y mêlé : séparé maintenant? de tte façon, même taxon!
140001 : ditto
140002: mais en majeure partie B. acutum - pllus spp?

**Comment by brouille** [comment]
140005
140006 : il n'y a pas d'annotations par les différents auteurs, simplement des notes de Dupret
140009
140014
140025 : det 2: verifier si v. subpiligera unculus est bien une annotation - si non, enlever et renuméroter det 3
140026 : ditto - je crains des copies automatiques ici

140033 : est-ce vraiment Drepanocladus subpiligerus ou var. subpiligerus que Dupret voulait dire? sp n'existe pas
plus. spp ds cet échantillon?

**Comment by Luciefortin** [comment]
140033: Dans Etude sur les Mousses de la région de Montréal, H. Dupret écrit à: Drepanocladus aduncus var. subpiligerus (Renauld): Il abonde en particulier dans les mares de la forêt du Domainte de Saint-Sulpice. Ce spécimen: Domaine du Sault
