### ISSUE TITLE
Mélanges

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-data#193]
140712 Mélange
140713 Avec H. hispidulum
140714 Mêlé à H. aduncum
140719 Avec quelques Brachythecium rivulare
140720 Il y a peut être aussi Amblystegium noterophilum (stérile)
140721 Mêlé avec quelques Amblystegium irriguum
140725 Avec Hygrophilum
140736 Affreux mélange
140742 Avec Amb. irrig. , E. strigos. et juratzkanum ? 
140752 Mêlé à Amblystegium serpens
140754 Il y a peut être quelques Amblystegium irriguum
140758 Léger mélange
140761 Etait mêlé à aducum var. aquaticum
140771 Affreux mélange avec Brachythecium acutum et chrysophyllum
140775 Mêlé à Brachythecium oxycladon
140777 Mélange !!! surtout Amblystegium varium
140810 Mélange
140811 mêlé à A. rip. à capillif etc.
140832 Anomodon attenuatus, et  Anomodon apiculatus [seul le premier indiqué sur fiche]

valider det [identifier spécimen] :
140738 Amblystegium varium var. nanum [non publié] = Hygroamblystegium varium ?
140739 Amblystegium varium var. juratzkanum [n.p.] = Amblystegium serpens ?
140740
140764 Amblystegium varium var. serpens [non publié] = Amblystegium serpens ?

140819 det orig Neveu ou Dupret?

140826 : 1 ou 2 spécimens?
140833: compléter localité

**Comment by brouille** [comment]
140846 avec qlq. orthotr. anomal
140854 malheur. mêlé à Eurhynch. hians, stér. ; Il est très difficile de trouver serpens, pur. ; il y a peut-être aussi A. varium
140855 il y a qlq. B. acutum
déterminations: est-ce que det 1 est det orig et det 2 une annotation ou est-ce un spécimen mélangé?
si annotation, svp ajouter annotation à Cratoneuron f.

140856 Amblystegium longifolium (riparium) : [id det 172849] le nom sci inscrit est A. longifolium (syn de Drepanocladus longifolius) MAIS si c'est riparium longifolium, alors le syn devient Leptodictyum riparium, ce qui me semblerait cohérent avec les autres récoltes en ce lieu - vérifier svp

140857 un peu mêlé à Drep. capillifolius
140859 avec fontinalis nitida ?

**Comment by Luciefortin** [comment]
Tous corrigés, 193 peut être fermé
