### ISSUE TITLE
Modification au paramètre de contrôle du champs "ordre de détermination"

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-data#2]
[Originally posted on GoogleCode (id 474) on 2013-03-08]

Présentement, le champs &quot;ordre de détermination&quot; ne peut contenir qu'un seul chiffre (donc, il limite le nombre d'annotations à 9). Cependant, je viens de rencontrer un cas où ce nombre s'élève à 10 (cependant, il se pourrait que l'on doive éventuellement diviser la fiche et les annotations). Il n'est pas impossible qu'il y ait plus de 10 annotations.

Svp modifier le paramètre pour accepter 2 chiffres.

La fiche: 12967
Détermination 249921 (devrait être 10 et non 9)

Luc

**Comment by geoffreyhall** [comment]
[Originally posted on GoogleCode on 2013-03-14 19:15Z]

Ordre de détermination agrandi à 2 chiffres (donc ≤ 99 déterminations), fiche 129697 mise à jour (10 inséré au bon endroit)
