### ISSUE TITLE
plus spp et autres

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-data#201]
141748 det 1: Brachythecium rivulare, dit Macoun = det de Macoun?
141749 En compagnie de Amblystegium fluviatile
141750 verbatim elev.
la fructification est de l'Amblyst. orthocladon Pal de B.
yes (Macoun) : est-ce une annotation det 2?
141751 y a-t-il une annotation de Cardot ou est-ce simplement in litt?
forme plus fine quel est ce rivulare mêlé à ochraceum [...]

**Comment by Luciefortin** [comment]
Tout corrigé
