### ISSUE TITLE
type potentiel

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-data#203]
141855 vérifier s'il pourrait s'agir d'une copie du type
voir sweetgum.nybg.org/vh/specimen.php?irn=388234 et http://www.tropicos.org/Name/35110894
Luc

**Comment by Luciefortin** [comment]
Pas un type, ni isotype. Type: Barbula melanocarpa (Müll. Hal.) Kindb. Cat. Canad. Pl. 54, Yale B.C.
