### ISSUE TITLE
type

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-data#204]
141889 Bryum camptoneurum type original [isotype? MO dit holotype: herb. Thériot]

**Comment by brouille** [comment]
est-ce que la mention: "Approuvé par Arnelle en février 1914" est un stet et donc une annotation?

**Comment by Luciefortin** [comment]
Type

**Comment by Luciefortin** [comment]
Bryum pseudotriquetrum aristatum, Exsiccata Holzinger no 347, pour correction Taxon 2196. Les entrées de cnabh, et tous No. 347 ont été mis Taxon; Bryum pseudotriquetrum.
Type Bryum pseudotriquetrum var. aristatum Thériot ined.
