### ISSUE TITLE
loc, plu sspp, etc.

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-data#206]
141912 valider localité svp

141919 svp vérifier orthographe du nom sci Bryum cirrhatum (Hedw.) With. : était-il écrit cirratum ou cirrhatum ? Avec ces auteurs, ce devrait être cirratum - mais si les auteurs ne sont pas mentionnés, ce pourrait être Hoppe & Hornschuch plutôt. 
cirratum est improbable puisque l'espèce n'est connue que de la côte ouest
cirrhatum est possible et son syn serait Ptychostomum pallescens, une espèce présente dans l'est
il faudra peut-être valider la det du spécimen
selon le cas, il faudra annoter avec le nom acc approprié

141920 Bryum erythrocarpum - c'est un nom illeg. mais je suis incapable de trouver à quoi il correspond fide BFNA - est-il possible d'identifier ce spécimen à nouveau pour déterminer ce qu'il en est? la bd taxo est bien approximative présentement

141922 svp valider que le spécimen est bien  Ptychostomum pallescens car la taxonomie liée à ce nom est complexe (voir Taxon id 2196)
141923 id
et: Mêlé à Brachytecium acutum et autres - dans spécimen ou habitat?
141924, 141925, 141926, 141928 ibid
141927 la date correspond à celle des types à P (voir Taxon 2196) - cependant, hab est savane ici, vs tourbière à P - par contre, le nom ne semble pas avoir été publié et P a inscrit que le statut est incertain - ce n'est sans doute pas un type au sens strict
Mêlé à H. intermedium : spécimen ou habitat?

**Comment by Luciefortin** [comment]
Tous corrigés
