### ISSUE TITLE
problèmes et mélanges

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-data#212]
142172 revoir l'histoire de détermination - est-ce bien ainsi?
William : quelles initiales? déjà ds bd people?
142175 avec oxycladon dent
142176 localité: Nomainio [n'existe pas] ne serait-ce pas plutôt Nanaimo?
142185 léger mélange à oxycladon, rivulare etc.
142187 et du Mnium cinclidio
142193 à 142200 verbatim alt et coordonnées
142203  mais bien mêlé avec H. arcuatum, précieux à cause des capsules d'arcuatum, un peu jeunes
142208 Mostly B. acutum, avec B. rivulare
142211 Mêlé à Amb. irriguum f. mariana
142214 Avec velutinum
142223 verif localité
142225 verif det - det par?; Ok dit Theriot: annotation? [OK à quoi? var. ou f.?]
valider det3
142226 det1 de Beaulac: sp seule ou var? det2 annotation de Dupret?
je crois que Beaulac a déterminer l'sp. et Dupret a ajouté la var. - les données ont été interverties
142228 svp clarifier les déterminations - les notes sont difficiles à attribuer et mettre en ordre
det 1 de Beaulac est Hypnum ou Drep. uncinatus?
142229 clarifier dets svp
valider det 3

**Comment by Luciefortin** [comment]
Tout corrigé
