### ISSUE TITLE
données manquantes et plus spp

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-data#213]
142235 det 2 Calliergon giganteum : det par qui?
142237 il y a 2 spécimens, tous deux notés sur une même fiche - il faut séparer les fiches svp [peu importe les doubles] - aussi: mêlé à capillifolius [spécimen mélangé?]
svp annoter chaque sp par le nom accepté
142238 petit sachet : s'il s'agit d'un autre spécimen, il faut le séparer et faire une fiche
142241 det 1: svp valider si bon nom car ds aucune bd
déterminer à nouveau pr identification svp
142247 c'est flexilis dit Best  : det de Best ou annot de Best?
mêlé à qlq. riparium : plus spp?
142249 il semble y avoir plus. spécimens à séparer svp
Drepanocladus subpiligerus n'existe pas - re-déterminer svp pour confirmer det2
142250 Mêlé avec qlq. D. Drummondii
142252 je crois qu'il y a plusieurs sortes de mousses ici et pas seul. intermedius - oui, il y a qlques brins de Drep. capillifolius forma fallax
142254 det 2 Drepanocladus aduncus f. subpiligerus : par qui?
svp valider det 3
très joli mélange : plus spp?
140183 det 1: O.K. disent  Cheney, Grout, Thériot - sont-ce des annotations ?
142258 det 2 par Cheney (stet?)
142259 id
142264 det 1: est-ce bien comme sp que la plante est identifiée ou comme var de pusillum?
142273 pourquoi hésitation entre récolteurs? et pourquoi alors assigner Dupret ? valider svp
142294 Avec Polytrichum juniperinum  Hedw. : pourquoi si det 1? était-ce un spécimen mélangé séparé ensuite?
142298 verbatim coordonnées?
142299-142316 verbatim coordonnées & alt?

**Comment by Luciefortin** [comment]
toutes corrections faites
