### ISSUE TITLE
Nouveau projet potentiel

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-data#3]
[Originally posted on GoogleCode (id 475) on 2013-03-08]

Geoff

Fiche 129705

Dans le champs note sur le spécimen: &quot;Flora Inventory of the 7 X 7 km area at 45°56'N 75°51'W, 500-1830' &quot;

Cela me semble être un projet et ne devrait pas être dans note ms ds projet. Qu'en penses tu?

Luc

**Comment by geoffreyhall** [comment]
[Originally posted on GoogleCode on 2013-03-14 15:17Z]

projet créé, 8 fiches mises à jour
