### ISSUE TITLE
pourquoi avoir conservé cette entrée?

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-data#315]
208078
aucune donnée taxo - cela ne vaut rien - pourquoi conserver?
Luc

**Comment by herbier** [comment]
Nous sommes déjà au courant.  Sarah et moi nous avons convenu d'attendre avant de supprimer la fiche jusqu'à ce que tous les spécimens de l'année en question provenant de Stu soient numérotés pour être certain que le spécimen n'existe pas.

Geoff
