### ISSUE TITLE
Carex festucacea au QC

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-data#33]
[Originally posted on GoogleCode (id 1493) on 2014-11-26]

GEoff

Selon VASCAN, Carex festucacea n'est pas au Québec. Pourtant MT a des spécimens de cette espèce, apparemment non révisés. Serait-il possible de les valider éventuellement pour régler ce problème?
ex: 69129-31

Me laisser savoir s'il reste des spécimens au QC afin de corriger VASCAN (ou pas).

Luc

**Comment by geoffreyhall** [comment]
[Originally posted on GoogleCode on 2014-11-28 19:30Z]

Les 3 spécimens en question (MT-69129/) ont été saisis par Madeleine Roy en 2006 à l'époque quand on lui demandait de saisir à partir de listes (ex. Andrew F. Holmes à MTMG).  La localisation des spécimens à été changé de "à MT" à "unknown" et la remarque générale suivante a été ajoutée à chaque spécimen "Spécimen non retrouvé par Geoffrey Hall lors de la saisie complète de la section Ovales fin 2010—début 2011, et absent depuis (2014-11-27)".  La répartition connue de Carex festucacea se situe bien au sud du Québec et l'espèce ne devrait pas être considérée comme étant présente ici.
