### ISSUE TITLE
coordonnées 

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-data#339]
212052 GEoff: sur cette fiche, tu notes: latitude/longitude calculated by G. Hall 2016-03-21
pourtant, tu inscris les coordonnées dans les champs de lat long originale - il me semble que même si elles sont inscrites sur le spécimen, ces coordonnées ont été déterminées par un autre que le récolteur - ne serait-il pas mieux de les noter dans les champs verts foncés?
C'est un cas intermédiaire, j'en convient
Luc

**Comment by herbier** [comment]
d'accord, modifié sur la fiche
