### ISSUE TITLE
Carex straminea : spécimens du QC

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-data#34]
[Originally posted on GoogleCode (id 1516) on 2014-12-11]

Geoff: 
Carex straminea n'est pas rapporté du QC et est exclu du CAnada. Pourtant, quelques spécimens à ce nom subsistent toujours dans la bd, aux fiches:
69034, 69035
et il subsiste une mention pour TN: 95904

Il faudrait réviser ces spécimens, éventuellement.

Tout le reste a été corrigé

Luc

**Comment by geoffreyhall** [comment]
[Originally posted on GoogleCode on 2014-12-11 14:12Z]

Ces 3 spécimens ne sont pas à MT, ayant été saisis par Madeleine et Denise à partir de listes fournies par Stuart.  J'ai changé leur statut à "elsewhere".  Ce n'est pas la première fois que des spécimens saisis par ces 2 bénévoles à partir de listes qui sont absents de MT se retrouvent avec le statut "à MT" dans la base de données.  Lors de l'importation, apparemment, il n'y avait pas de souci ou de moyen à faire autrement.
