### ISSUE TITLE
détermination originale improbable

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-data#340]
212047 la det1 Astragalus labradoricus me semble improbable pour cette localité
je présume que les spécimens n'ont pas encore été validés?
Luc

**Comment by herbier** [comment]
Rien des étudiants n'a été validé encore.  Claude m'aide à mettre de côté tous les problèmes potentiels et il l'a mis de côté.  Cette collection a été passé en revue en 2007 lors de la correction mais j'ai vérifié dans l'armoire et il n'y a pas de correction sur le spécimen.  En passant, c'est un Vicia cracca.
Geoff
