### ISSUE TITLE
Cuba : 115381

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-data#424]
115381 Ilyptis pedalipes : svp vérif orthographe car ce nom de genre ne semble pas exister 
TAxon 7260

Luc

**Comment by geoffreyhall** [comment]
Sur l'étiquette le soi-disant "Ilyptis pedalipes Griseb." est en réalité "Hyptis pedalipes Griseb."  Quant à l'ID de taxon 7260 dans la table TAXON, le premier nom, Ilyptis pedalipes Grisebach, devrait être remplacé par le 2e, Hyptis pedalipes Grisebach.  Idem pour l'ID de spécimen 115381, dét. 1.

Geoff

**Comment by geoffreyhall** [comment]
Idem pour l'ID de spécimens 115382 et 115383, dét. 1.

Geoff

**Comment by brouille** [comment]
Hyptis pedalipes = Cyanocephalus pedalipes
annoté électroniquement - à annoter avant photo éventuelle
Luc
