### ISSUE TITLE
192986 Spécimen WAT sans photo

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-data#428]
Geoff
Le Spécimen WAT 192986 est sans photo; pourtant il est dans une séquence photographiée - il pourrait ne pas avoir été associé correctement ou ne pas avoir été photographié
Luc

**Comment by brouille** [comment]
Spécimen WAT 193011 sans étiquette

**Comment by geoffreyhall** [comment]
--192986 sans photo à cause d'erreur humaine, récolte de John Semple prêtée à John Semple (MT14-06); photo à faire au retour du prêt

--193011 sans étiquette est la partie C de 3 planches d'une récolte de John Semple prêtée à John Semple (MT14-06); étiquette à faire au retour du prêt

Geoff
