### ISSUE TITLE
Rosa : spécimens de B. Ertter

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-data#540]
Pourquoi tous les spécimens de Barbara Ertter collecté dans l'ouest des USA sont-ils tous "unknown" ?

Pas à MT?

Luc

**Comment by geoffreyhall** [comment]
Il est prudent de laisser les 25 cas comme "unknown" parce qu'ils ne se sont pas encore apparus suite à l'intégration des rosiers confiés à Amy en 2012 et d'autres que j'ai trouvés plus tard sur divers étagères au 2e.  Il y en a peut-être entre le montage et la photo, mais personnellement, je n'ai pas de souvenir d'en avoir eu d'Ertter entre les mains.  2 autres hypothèses :  (1) les données ont été reçues et importées (par "unknown", marqueur d'importation "ROSA"), sans les spécimens, (2) ils sont classés dans la collection MAIS j'ai tout vérifié et aucun des 25 ne se trouve à sa place.
---Geoff
