### ISSUE TITLE
Frère Amédée = Amédée Cormier

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-data#579]
Frère Amédée 115
est-il la même personne que
Fr. Amédée Cormier 11562 ?

Luc

**Comment by geoffreyhall** [comment]
Il s'agit de frères appartenant à deux congrégations distinctes :
Frère Amédée, s.c. (membre des Fratres a Sacratissimo Corde Jesu, ou des frères du Sacré-Coeur)
Frère Amédée Cormier, s.m. (membre de l'Institutum Fratrum Maristarum a Scholis. ou des frères maristes)
Le premier était actif entre 1950 (Trois-Rivières) et 1951 (Saguenay), tandis que le 2e n'est connu que d'une récolte en 1945 (Gracefield, La Vallée-de-la-Gatineau).
Geoff
