### ISSUE TITLE
Vérification de MT00180214 -- Monarda fistulosa Linnaeus var. mollis

### ISSUE THREAD

**Issue by AlexBERGER0N** [irbv-collections/MT-data#582]
Salut Geoff,

Possible pour toi de contre-vérifier le spécimen MT00180214 -- Monarda fistulosa Linnaeus var. mollis ?

Il n'est pas présent au QC d'après VASCAN: https://data.canadensys.net/vascan/taxon/6419?lang=fr

Je prépare une publication dans laquelle je mentionnerai cet ajout. 

À mon avis, la petite population du M. fistulosa var. mollis avait les caractéristiques d’un événement de naturalisation (provenant de l’horticulture) plutôt que celles d’une population indigène et rare, jamais observée par les botanistes. 

Sinon, j'espère que tu vas bien. De mon côté, je viens de déposer ma thèse, et j'ai enfin des temps libres! 

Alexandre

**Comment by AlexBERGER0N** [comment]
À bien y penser, il faudrait vérifier tous les spécimens de MT de Monarda fistulosa sensu lato afin de s'assurer que des vars. mollis n'auraient pas échappé à la vigilance des botanistes prédécesseurs, et que ce taxon soit bel et bien indigène au Québec. Je pourrais écrire un court paragraphe là-dessus dans ma publication.

**Comment by geoffreyhall** [comment]
Salut Alexandre,

Merci des nouvelles.  Je ne suis pas à Montréal.  Dès que possible (début de la semaine prochaine), je ferai un retour depuis l'herbier.

Geoffrey

**Comment by AlexBERGER0N** [comment]
Merci Geoff!

**Comment by geoffreyhall** [comment]
Bonjour Alexandre,
Je constate que rien dans ton armoire n'a été touché.  J'estime qu'il y a environ 150 planches prêtes à intégrer, et 150 chemises de spécimens non montés.  Je pourrais transférer les spécimens montés dans l'armoire à photographier, et ainsi vérifier si MT-180214 est dans ce groupe.  Désires-tu que je fasse ce transfert, ou as-tu besoin de les garder dans ton armoire encore?
Quant au taxon en question, au Québec, MT possède ± 25 planches de la var. mollis, annotées le 30 oct. 2013 par Fanny Theurel.  Fanny était une stagiaire ici, en provenance du Jardin botanique de l'Université de Franche-Comté et de la Ville de Besançon.  J'avais oublié cette activité, mais j'ai dû approuver son travail à l'époque, et, en jetant un coup d'oeil maintenant, je trouve qu'elle a bien annoté les vars. fistulosa et mollis.
À cause de la pandémie, personne ne peut consulter la collection, je n'ai aucune aide, et j'ai beaucoup de demandes.  Donc je dois poser des questions.  (1) Est-il important de consulter tous les 25 spécimens avant que la situation retourne à une situation d'accès libre?  (2) Peux-tu déterminer la var. à partir d'une image (voici 2 ex. de fistulosa <http://media.canadensys.net/mt-specimens/large/MT00206312.jpg>, <http://media.canadensys.net/mt-specimens/large/MT00208284.jpg>)  (3)  Si les images ne suffisent pas pour vérifier la var., les données de récolte associées aux planches te sont-elles utiles?
Je pourrais faire des images de quelques planches ou de toutes les planches, si elles sont utiles à ta rédaction.  Ça prendrait un peu de temps.  Si les images ne servent à rien, je vais reporter le projet, bien sûr.
Donne-moi des nouvelles quand tu auras le temps.  D'ici là, pensons à André qui nous a quitté,
Geoffrey

**Comment by AlexBERGER0N** [comment]
Bonjour Geoffrey,
Je commente sous forme de questions-réponses.

GH1 : Désires-tu que je fasse ce transfert, ou as-tu besoin de les garder dans ton armoire encore?
AB1.1 : Oui, ce serait très apprécié. Merci.
AB1.2 : À propos des 150 spécimens non montés, possèdent-ils un code institutionnel MTXXXXXXXX?
AB1.3 : Je remarque aussi en constatant les fichiers dwca-mt-specimens-v14.9 que certains de mes spécimens, pourtant légués depuis longtemps, n’y sont pas (cité ci-dessous). Possèdent-ils un code institutionnel MTXXXXXXXX?

10001
Polypodium virginianum
Notre-Dame-de-l'Île-Perrot
Bois de la Pointe Est à l’île Perrot (secteur nord-est) 
585594; 5026627
Prucherais
Alexandre Bergeron
17-juin-10

10002
Lycopodium annotinum
Notre-Dame-de-l'Île-Perrot
Bois de la colline à l’île Perrot (secteur nord-ouest)  
581923; 5024703
Érablière rouge
Érable rouge, pin blanc
Alexandre Bergeron
22-juin-10

10003
Woodwardia virginica
Notre-Dame-de-l'Île-Perrot
Bois de la colline à l’île Perrot (secteur nord-ouest)  
582109; 5025351
Tourbière
Sphagnum fallax, osmonde cannelle
Alexandre Bergeron
28-juin-10

10004
Botrychium dissectum f. obliquum
Montréal
Arboretum Morgan
581188; 5031592
Prucherais, bord d'un sentier humide
Leersia oryzoïdes, osmonde cannelle
Alexandre Bergeron & Julie Munger
24-août-10
Les individus étaient à quelques mètres de B. dissectum f. dissectum

10005
Botrychium dissectum f. dissectum
Montréal
Arboretum Morgan
581188; 5031592
Prucherais, bord d'un sentier humide
Leersia oryzoïdes, osmonde cannelle
Alexandre Bergeron & Julie Munger
24-août-10
Les individus étaient à quelques mètres de B. dissectum f. obliquum

10006
Dryopteris goldiana
Montréal
Bois de Saraguay
45°30'48.6"; 73°44'25.1"
Érablière à caryer en bordure d'un marécage
Acer saccharum, Acer nigrum, Quercus macrocarpa
Alexandre Bergeron
04-sept-10
Probablement l'un des parents de D. x neo-wherryi (voir MT, Bergeron. A., 04-sept-2010, no 10008)

10007
Dryopteris marginalis
Montréal
Bois de Saraguay
45°30'48.6"; 73°44'25.1"
Érablière à caryer en bordure d'un marécage
Acer saccharum, Acer nigrum, Quercus macrocarpa
Alexandre Bergeron
04-sept-10
Probablement l'un des parents de D. x neo-wherryi (voir MT, Bergeron. A., 04-sept-2010, no 10008)

10008
Dryopteris x neo-wherryi
Montréal
Bois de Saraguay
45°30'48.6"; 73°44'25.1"
Érablière à caryer en bordure d'un marécage
Acer saccharum, Acer nigrum, Quercus macrocarpa
Alexandre Bergeron
04-sept-10
Population de 5 individus; première mention au Québec

GH2 : Est-il important de consulter tous les 25 spécimens avant que la situation retourne à une situation d'accès libre? 
AB2.1 : NON. Maintenant que je sais que la variété a bel et bien été recensée au Québec, ce travail perd en utilité. À vrai dire, je suis d’avis que les annotations de Fanny Theurel et tes contre-vérifications sont justes. La variété mollis n’est pas très difficile à identifier.
GH2.2 : Peux-tu déterminer la var. à partir d'une image?
AB2.2.1 : Ce travail n’est plus nécessaire.
GH2.3 : Si les images ne suffisent pas pour vérifier la var., les données de récolte associées aux planches te sont-elles utiles?
AB2.2.1 : OUI, svp! Dans les fichiers dwca-mt-specimens-v14.9, il n’y a que 2-3 mentions pour le Québec. S’il y a plus de données, je pourrais me faire une meilleure idée sur l’indigénat de l’espèce et faire une courte note là-dessus dans mon article. Cela mettrait par écrit ces nouvelles connaissances.

AB3 : En fait, je rédige un article qui liste la flore forestière de l’île de Montréal et de ses environs. J’aurais donc plusieurs informations à te demander au fil de ma rédaction. Comme je suis conscient que tu es seul à l’herbier, je te ferai des demandes par bloc. J’ai d’autres questions précises, mais je me les garde pour une autre fois. Allons-y stratégiquement! Là, je suis dans les ptéridophytes, par exemple.

As-tu un numéro de téléphone où je peux te rejoindre à l’herbier (et un horaire précis de travail)? Parfois, c’est plus simple de vive voix. 

Je pourrais aussi te donner de mes nouvelles. J’ai effectivement appris le décès d’André, ce qui m’attriste grandement. Une grosse perte pour la botanique québécoise!

Alexandre
