### ISSUE TITLE
Mauvaise photo associée à bd

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-data#583]
1666 Euthamia graminifolia Poisson 67

photo associée: 16666 Lonicera morrowii J.P. Bernard

Svp, associer la bonne photo au spécimen, si vraiment une a été prise. Sinon enlever. Vérifier si photo associée au bon spécimen aussi

Luc

**Comment by geoffreyhall** [comment]
On ne peut pas facilement enlever une photo, mais on peut l'écraser avec une nouvelle qui porte le même numéro.  Si possible me donner l'Euthamia 1666 pour ce faire.  Je m'occupe de renommer la photo du Lonicera pour que le numéro 16666 soit correct aussi.  Merci.
Geoff

**Comment by brouille** [comment]
J’ai sorti le spécimen. Je te le donnerai aujourd’hui
Luc

De : geoffreyhall ***@***.***>
Répondre à : irbv-collections/MT-data ***@***.***>
Date : lundi 14 mars 2022 à 11:05
À : irbv-collections/MT-data ***@***.***>
Cc : Luc Brouillet ***@***.***>, Author ***@***.***>
Objet : Re: [irbv-collections/MT-data] Mauvaise photo associée à bd (Issue #583)


On ne peut pas facilement enlever une photo, mais on peut l'écraser avec une nouvelle qui porte le même numéro. Si possible me donner l'Euthamia 1666 pour ce faire. Je m'occupe de renommer la photo du Lonicera pour que le numéro 16666 soit correct aussi. Merci.
Geoff

—
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Firbv-collections%2FMT-data%2Fissues%2F583%23issuecomment-1066914195&data=04%7C01%7Cluc.brouillet%40umontreal.ca%7C3de5e2f430cc4c4f4ce908da05cc1267%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637828671299945841%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DV7yvQ3ON5%2Fg3z0ilP8AdTtQjfgHvOT3TGMySmcSYTw%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACZV5Y2B7ICR6QDH6ZNUTCDU75ITNANCNFSM5QVNBIEQ&data=04%7C01%7Cluc.brouillet%40umontreal.ca%7C3de5e2f430cc4c4f4ce908da05cc1267%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637828671299945841%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ra5F03kGeMtP4R%2BtaSnRgdFGJOMmObrrgxHTamHV%2FaI%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cluc.brouillet%40umontreal.ca%7C3de5e2f430cc4c4f4ce908da05cc1267%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637828671299945841%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OOb%2BtjOXUJt9ouvCVZsywVggUfTOFPD%2BdvWvh5gQgQg%3D&reserved=0> or Android<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cluc.brouillet%40umontreal.ca%7C3de5e2f430cc4c4f4ce908da05cc1267%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637828671299945841%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Aq2Ze6R310PDcpaTRswlKj%2FV4nJv3DlP3Z55yht%2BQwg%3D&reserved=0>.
