### ISSUE TITLE
Carex careyana au QC

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-data#6]
[Originally posted on GoogleCode (id 753) on 2013-10-28]

Geoff

spécimen 108474
P. Dansereau 470610-64
Carex careyana rapporté du Québec

Or dans VASCAN, j'ai cette espèce comme exclue pcq misidentification

Le spécimen et la localité sont-il sexacts?

Luc

**Comment by geoffreyhall** [comment]
[Originally posted on GoogleCode on 2013-11-12 20:54Z]

Carex careyana ressemble à Carex plantaginea; après vérification à MT, il n'y a ni
---spécimens de Carex careyana du Québec, ni
---spécimens de Dansereau de Carex plantaginea du Québec, ni
---spécimens de Carex careyana révisé à Carex plantaginea du Québec

Le spécimen de Dansereau a dû être relevé à partir de notes ou de spécimens déposés ailleurs; son identification est sûrement erronée
