### ISSUE TITLE
nom accepté pour Polygonum heterophyllum Lindm. v. litorale (Link) Lindm.?

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-data#73]
[Originally posted on GoogleCode (id 664) on 2013-06-27]

Sur l'étiquette:  Polygonum heterophyllum Lindm. var. litorale (Link) Lindm.

Polygonum heterophyllum Lindman (incluant la var. litorale, entre autres):
http://www.biodiversitylibrary.org/page/15072903#page/780/mode/1up
http://www.biodiversitylibrary.org/page/15072903#page/781/mode/1up

Polygonum littorale Link:
http://www.biodiversitylibrary.org/page/7451897#page/392/mode/1up
http://www.biodiversitylibrary.org/page/7451897#page/393/mode/1up

selon Tropicos, Polygonum littorale Link est le basionyme de Polygonum aviculare var. littorale (Link) Mert. &amp; W.D.J. Koch [aut. différentes dans la base de données MT]:
http://www.tropicos.org/Name/100387610
http://www.tropicos.org/Name/26001514

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-28 13:13Z]

Polygonum heterophyllum Lindm. var. litorale (Link) Lindm. = Polygonum aviculare subsp. aviculare
