### ISSUE TITLE
Reclassement Polygonaceae

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-data#74]
[Originally posted on GoogleCode (id 665) on 2013-06-27]

Noms acceptés pour ;

Polygonum punctatum var. aquatile (Mart.) Fassett

Polygonella fimbriata var. robusta (Small) Horton

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-28 12:32Z]

Polygonella fimbriata var. robusta (Small) Horton = Polygonum nesomii T.M. Schuster & Reveal

Polygonum punctatum var. aquatile = Persicaria punctata (Elliott) Small
