### ISSUE TITLE
Dans la table TAXON, il y a 2 autorités pour Persicaria lapathifolia

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-data#75]
[Originally posted on GoogleCode (id 670) on 2013-07-04]

<b>(This is the template to report a data issue. For another issue, change the</b>
<b>template above.)</b>

<b>What data issue did you discover in the database?</b>

Persicaria lapathifolia (Linnaeus) Delarbre (apparaît 8 fois comme nom accepté dans le modèle de saisie SPÉCIMEN)

Persicaria lapathifolia (Linnaeus) Gray (apparaît 458 fois comme nom accepté dans le modèle de saisie SPÉCIMEN)

http://www.tropicos.org/NameSearch.aspx?name=Persicaria+lapathifolia&amp;commonname=

Geoffrey Hall

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-07-04 17:53Z]

Fait.

La correction se fait automatiquement dans la base de données. Pas de problème.
