### ISSUE TITLE
pennsylvanica devrait être pensylvanica

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-data#76]
[Originally posted on GoogleCode (id 685) on 2013-07-25]

<b>(This is the template to report a data issue. For another issue, change the</b>
<b>template above.)</b>

<b>What data issue did you discover in the database?</b>
Taxon ID 9456 :
Persicaria pennsylvanica var. laevigata

devrait être

Persicaria pensylvanica var. laevigata

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-07-26 12:35Z]

Persicaria pennsylvanica var. laevigata

était tel quel dans la bd spécimens - j'ai corrigé les deux
