### ISSUE TITLE
Source link does not support, or no longer supports, accepted name

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-data#77]
[Originally posted on GoogleCode (id 696) on 2013-08-12]

(This is the template to report a data issue. For another issue, change the template above.)

<b>What data issue did you discover in the database?</b>

Please update source link to support accepted name and synonym (Taxon ID 16671):

In the Taxon table, Persicaria decipiens is the accepted name for synonym Polygonum serrulatum.  This is supported by various sources like eFlora's Madagascar Catalogue and Kew's Flora Zambesiaca (http://www.efloras.org/florataxon.aspx?flora_id=12&amp;taxon_id=250082762; http://apps.kew.org/efloras/namedetail.do?flora=fz&amp;taxon=11680&amp;nameid=29909; http://redlist.sanbi.org/species.php?species=2224-14; http://www.ispot.org.za/species_dictionary/Persicaria%20decipiens).

The source link currently provided in  the Taxon table (http://www.theplantlist.org/tpl/record/kew-2573819) states that Persicaria serrulata is the accepted name for synonym Polygonum serrulatum.

Moreover, Tropicos and some The Plant List pages separate serrulata from decipiens, contradicting Kew's own Flora Zambesiaca (http://www.tropicos.org/Name/100349030; http://www.theplantlist.org/tpl/record/kew-2572330; http://www.tropicos.org/Name/50156630; http://www.theplantlist.org/tpl/record/kew-2571906).

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-08-20 17:53Z]

source modifiée pour TROPICOS sous P. decipiens (voir synonyms)
majorité des flores reconnaissent serrulatum comme syn de decipiens
TROPICOS est une référence aux noms, donc quand on met un nom, on obtient les symonymes homotypiques, mais pas nécessairement le nom accepté - ne pas confondre
