### ISSUE TITLE
Polygonaceae :  taxons à ajouter, noms acceptés à déterminer

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-data#78]
[Originally posted on GoogleCode (id 703) on 2013-08-21]

<b>(This is the template to report a data issue. For another issue, change the</b>
<b>template above.)</b>

<b>What data issue did you discover in the database?</b>

6 taxons et noms acceptés à ajouter pour:

(1) Ontario et USA
Polygonum lapathifolium L. var. incarnatum Wats

(2) Alberta
Polygonum lapathifolium var. lapathifolium

(3) Saskatchewan
Persicaria tomentosa (Schrank) E.P. Bicknell

(4) Québec
Polygonum tomentosum Schrank var. incanum (Schmidt) Gürke

(5) USA
Persicaria opelousana (Riddell) Small

(6) USA
Polygonum hydropiperoides var. opelousanum (Riddell) Stone

aussi:
(a) je vais faire serrer Polygonum aviculare f. caespitosum (déjà dans la bd, MT-62738, Rimouski, dét. Lepage) dans les chemises de Polygonum aviculare à moins qu'il y a un autre nom accepté

(b) en général, je vais considérer que caespitosum = cespitosum, à moins qu'on ne me dise le contraire

---Geoff

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-08-21 21:03Z]

Polygonum lapathifolium var. lapathifolium = Persicaria lapathifolia
Persicaria tomentosa = Persicaria lapathifolia

Persicaria opelousana (Riddell) Small = Persicaria hydropiperoides
Polygonum hydropiperoides var. opelousanum (Riddell ex Small) W. Stone = Persicaria hydropiperoides

il reste (1) et (4), s"ils existent...

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-08-22 17:13Z]

Polygonum lapathifolium L. var. incarnatum Wats = Persicaria lapathifolia

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-08-23 13:22Z]

Polygonum tomentosum Schrank var. incanum (Schmidt) Gürke = Persicaria lapathifolia

déduit indirectement des autres synonymes avec incanum, tous syn. de P. l.
le nom de Gürke n'est pas ds les bd ms semble plausible considérant le nombre de flores auxquelles il a participé
