### ISSUE TITLE
Polygonaceae :15 taxons à ajouter, noms acceptés à déterminer

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-data#84]
[Originally posted on GoogleCode (id 732) on 2013-10-11]

<b>(This is the template to report a data issue. For another issue, change the</b>
<b>template above.)</b>

<b>What data issue did you discover in the database?</b>

15 noms scientifiques et noms acceptés à ajouter pour:

(1) Yukon, Mackenzie et Alaska
Polygonum bistorta subsp. plumosum (Small) Hultén

(2) Alaska
Polygonum plumosum

(3) Alaska
Polygonum alaskanum (Small) W. Wight

(4) Franklin
Polygonum viviparum L. f. ramosum M. P. Porsild

(5) Asie
Atraphaxis spinosa L. var. sinaica (Jaub. &amp; Sp.) Boiss.

(6) USA
Oxytheca dendroidea Nutt.

(7) USA
Eriogonum wrightii Torrey subsp. trachygonum (Torr.) Stokes

(8) USA
Eriogonum wrightii Torr. var. membranaceum Stokes

(9) USA
Eriogonum wrightii Torr. var. subscaposum Watson

(10) USA
Eriogonum vimineum Dougl. subsp. nidularium (Cov.) Stokes

(11) USA
Eriogonum vimineum Dougl. var. caninum Greene

(12) USA
Eriogonum vimineum Dougl. subsp. baileyi (Watson) Stokes var. elegans (Greene) Jepson

(13) USA
Eriogonum vimineum Dougl. subsp. gracile (Benth.) Stokes var. agninum (Greene) Stokes

(14) USA
Eriogonum vimineum Dougl. subsp. typicum Stokes var. caninum (Greene) Stokes

(15) USA
Eriogonum vimineum Dougl. subsp. densum (Gr) Stokes

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-10-11 20:34Z]

(1) Yukon, Mackenzie et Alaska Polygonum bistorta subsp. plumosum (Small) Hultén = Bistorta plumosa
(2) Alaska Polygonum plumosum = Bistorta plumosa
(3) Alaska Polygonum alaskanum (Small) W. Wight = Aconogonon alaskanum

(5) Asie Atraphaxis spinosa L. var. sinaica (Jaub. & Sp.) Boiss.= Atraphaxis spinosa
(6) USA Oxytheca dendroidea Nutt. = Oxytheca dendroidea
(7) USA Eriogonum wrightii Torrey subsp. trachygonum (Torr.) Stokes = Eriogonum wrightii var. trachygonum
(8) USA Eriogonum wrightii Torr. var. membranaceum Stokes acc
(9) USA Eriogonum wrightii Torr. var. subscaposum Watson acc
(10) USA Eriogonum vimineum Dougl. subsp. nidularium (Cov.) Stokes = Eriogonum nidularium
(11) USA Eriogonum vimineum Dougl. var. caninum Greene = Eriogonum luteolum var. caninum
(12) USA Eriogonum vimineum Dougl. subsp. baileyi (Watson) Stokes var. elegans (Greene) Jepson = nom. illeg. hom. = Eriogonum elegans
(13) USA Eriogonum vimineum Dougl. subsp. gracile (Benth.) Stokes var. agninum (Greene) Stokes = Eriogonum cithariforme var. agninum
(14) USA Eriogonum vimineum Dougl. subsp. typicum Stokes var. caninum (Greene) Stokes = SUBSP. TYPICUM nom. inval. = subsp. vimineum = Eriogonum luteolum var. caninum
(15) USA Eriogonum vimineum Dougl. subsp. densum (Gr) Stokes = pas de subsp. avec ces auteurs ms var. densum (Greene) S. Stokes = Eriogonum polycladon

(4) Franklin
Polygonum viviparum L. f. ramosum M. P. Porsild
Je n'ai pu trouver de f. ramosum Porsild - IPNI a f. ramosum (Nakai) T.Shimizu
Cela reste à résoudre

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-10-21 18:22Z]

(4) Franklin
Polygonum viviparum L. f. ramosum M. P. Porsild = Bistorta vivipara
la f. ramosum Porsild ne se trouve pas ds les bd
