### ISSUE TITLE
Byrsonima verbascifolia a 2 auteurs

### ISSUE THREAD

**Issue by geoffreyhall** [irbv-collections/MT-data#89]
[Originally posted on GoogleCode (id 1680) on 2015-03-06]

<b>What data issue did you discover in the database?</b>
Dans table Taxon:
ID de taxon = 2243
Nom scientifique = Byrsonima verbascifolia
Auteur d'espèce = (Linnaeus) Richard ex Jussieu
Auteur accepté = (Linnaeus) de Candolle

NB :  &quot;Byrsonima&quot; paraît seulement dans les issues 1630 et 1671 de Diane Fournier (diverses espèces).  Celle recherchée, Byrsonima verbascifolia, n'y est pas, donc je dois créer une demande nouvelle.

Geoff

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-03-06 21:10Z]

Byrsonima verbascifolia (Linnaeus) Richard ex Jussieu = nom. illeg. = Byrsonima verbascifolia (Linnaeus) de Candolle

Cela explique la différence des auteurs. Probablement que le spécimen avait les premiers auteurs (erronés) et non les seconds.

Luc
