### ISSUE TITLE
MT173311 : détermination manquante ds bd

### ISSUE THREAD

**Issue by brouille** [irbv-collections/MT-data#9]
[Originally posted on GoogleCode (id 1369) on 2014-10-22]

Geoff

MT173311
Tu as négligé d'inscrire le nom de l'espèce que tu as re-déterminé en faisant l'entrée de ce spécimen (originalement C. artitecta)

Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-10-22 13:03Z]

Spécimen MT177151 Carex varia a besoin de re-détermination - aucune fournie lors de la numérisation

**Comment by geoffreyhall** [comment]
[Originally posted on GoogleCode on 2014-10-22 15:09Z]

Planche MT-173311 vérifiée, dét. ajoutée (Carex albicans var. albicans), nom du récolteur corrigé; planche MT-173312 vérifiée, 2 dét. ajoutées (Carex varia, Carex albicans var. albicans); planches voisines vérifiées mais aucun problème détecté; je ne sais pas pourquoi ces déterminations bien annotées sur les planches n'ont pas été correctement saisies ensuite

**Comment by geoffreyhall** [comment]
[Originally posted on GoogleCode on 2014-10-23 20:22Z]

MT177151: nouvelle dét. effectuée et ajoutée
