### ISSUE TITLE
Données à déplacer en masse d'un champs à l'autre

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-data#90]
[Originally posted on GoogleCode (id 10) on 2012-02-03 by amy.vandal.13]

<b>(This is the template to report a data issue. For another issue, change the</b>
<b>template above.)</b>

<b>What data issue did you discover in the database?</b>

Nous sommes tombés sur 3494 spécimens de plantes vasculaires qui ont un numéro d’enveloppe (normalement réservé aux bryophytes). Ils ont été remplis pour la plupart entre 1992 et 1998 et correspondent aux collections provenant de l’UQAM.

Cela pose potentiellement problème pour 889 bryophytes puisque les identifications ayant le même Numéro d’enveloppe sont automatiquement reportés dans le champ &quot;Autres spécimens dans l’enveloppe&quot;. Des spécimens de plantes vasculaires sont ainsi reportées dans la Base de données comme étant dans la même enveloppe que des bryophytes.

Y aurait-il moyen de réglé le problème automatiquement, comme par exemple en demandant à FileMaker de déplacer les valeurs d’un champs à un autre uniquement pour les non-bryophyte ? (l’alternative étant de corriger manuellement les 3494 entrées)

Merci

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2012-02-06 14:29Z]

envelopeNumber (e.g. u44) of the 3494 vascular plants has been moved to alternativeSpecimenNumber.
