### ISSUE TITLE
Information erronée dans le champ calculé "Autres spécimens dans l'enveloppe"

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-data#91]
[Originally posted on GoogleCode (id 34) on 2012-02-10 by amy.vandal.13]

<b>(This is the template to report a data issue. For another issue, change the</b>
<b>template above.)</b>

<b>What data issue did you discover in the database?</b>

Selon Lucie Fortin, l'information située dans le champ calculé &quot;Autres spécimens dans l'enveloppe&quot; serait erronée dans certains enregistrements pour les récolteurs Marie-Victorin et Marie-Anselme.

Ce pourrait être due en partie au fait qu'ils utilisaient les mêmes numéros de récolte à chaque année.

Il faudrait vérifier la formule qui permet de calculer automatiquement les ID des spécimens de bryophytes présents dans une même enveloppe.

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2012-02-16 14:53Z]

I'll need an example (2 specimenIDs)

**Comment by herbier** [comment]
[Originally posted on GoogleCode on 2012-02-17 16:52Z by amy.vandal.13]

If you search 
Ex 1
Collector: Marie-Anselme, Fr.
Collector number:197

You have 4 IDs (155875, 148706, 139266, 139265) for which there is 3 IDs in the field "Other specimens in the envelope",
But the envelope number is different for each of them and it is specified that there is only one specimen per envelope.

Ex 2
Collector: Marie-Anselme, Fr.
Collector number:195

ID 139245 and ID 155878 are said to be with together with 155876|155877 in the enveloppe in the field "Other specimens in the envelope".
But their envelope number is different and it is specified for 139245 and 155878 that there is only one specimen per envelope.

 Is it clear?

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2012-02-24 19:17Z]

Verify with Lucie.

New condition: only connect via envelopNumber & collectorNumber if the envelopeNumber is the same or empty (= envelopeNumberCountCalcul is not 1)

New formula:

If ( isBryophyte = "yes" ; If (envelopeNumberCountCalcul = 1 ; "" ; If ( envelopeNumberCountCalcul > 1 ; Substitute ( Substitute ( Substitute ( List ( SpecimenViaEnvelopeNumber::ID ) ; Char(13) ; "|" ) ; ID & "|" ; "" ) ; "|" & ID ; "" ) ; If ( collectorNumberCountCalcul > 1 and collectorNumber  ≠ "sn" ; Substitute ( Substitute ( Substitute ( List ( SpecimenViaCollectorAndCollectorNumber::ID ) ; Char(13) ; "|" ) ; ID & "|" ; "" ) ; "|" & ID ; "" ) ; "" ) ) ) )

**Comment by herbier** [comment]
[Originally posted on GoogleCode on 2012-03-21 18:00Z by amy.vandal.13]

La formule pour champ calculé "Autres spécimens dans l'enveloppe" a été changée. Elle tient maintenant uniquement compte des enveloppes qui ont le même numéro ou qui n'ont pas de numéro mais qui ont un récolteur & no de récolte identiques pour grouper les spécimens par enveloppe. 

Si ( isBryophyte = "yes"; Cas (
envelopeNumberCountCalcul > 1; Substituer ( Substituer ( Substituer ( Liste( SpecimenViaEnvelopeNumber::ID ) ; Caractere(13) ; "|" ) ; ID & "|" ; "" ) ; "|" & ID ; "" ) ; 
EstVide(envelopeNumberCountCalcul) And collectorNumberCountCalcul > 1 And collectorNumber  ≠ "sn" ; Substituer ( Substituer ( Substituer ( Liste ( SpecimenViaCollectorAndCollectorNumber::ID ) ; Caractere(13) ; "|" ) ; ID & "|" ; "" ) ; "|" & ID ; "" ) ; "")
;"")

Cela règle presque tous les cas problèmes, à l'exceptions d'une vingtaine qui seront à corriger manuellement.

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2012-03-21 21:25Z]

Great! I only updated the formula to English in the Google doc to be consistent.
