### ISSUE TITLE
Années manquantes dans la table Projet

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-data#92]
[Originally posted on GoogleCode (id 49) on 2012-02-17 by amy.vandal.13]

<b>(This is the template to report a data issue. For another issue, change the</b>
<b>template above.)</b>

<b>What data issue did you discover in the database?</b>

Aucune fiche ne contient d'année de début ni de fin de projet dans la table Projet. Au lieu, tous les champs de Date indiquent &lt;Table non liée&gt;. 

Il est impossible d'y rentrer de l'information, le message &quot;Impossible d'effectuer cette opération car la cible n'appartient pas à une table liée.&quot; apparaît lorsque l'on clique sur le champ.

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2012-02-20 15:30Z]

This issue was not related to the deletion of the specimenProject table. It was just an error on the form. Fixed now.
