### ISSUE TITLE
Confusion dans la gestion des spécimens empruntés

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-data#93]
[Originally posted on GoogleCode (id 81) on 2012-03-01 by amy.vandal.13]

<b>(This is the template to report a data issue. For another issue, change the</b>
<b>template above.)</b>

<b>What data issue did you discover in the database?</b>

Certaines incohérences apparaissent dans la section Gestion en raison de son utilisation dans les prêts en plus des échanges. 

Les spécimens que MT a empruntés et pour lesquels on souhaite garder l’information (par exemple parce que l’on y a effectué une révision) sont entrés dans la section gestion comme spécimens provenant de, par ex, CAN et retourné à CAN.

On coche à MT : « yes » si on sait que l’on a un doublon dans la collection et « Unknown » lorsque l’on ignore si on a un doublon dans notre collection.  Ceci implique que le spécimen de CAN et le notre sont situé sur une seule et même fiche (un ID pour deux objects physiques) bien que les annotations et l’historique peuvent être différents sur les deux objets. 

Cela entre une certaine confusion puisque un spécimen clairement identifié comme retourné à CAN est aussi identifié comme de localisation inconnue. Il est aussi impossible de connaître quelles informations sont associées à quel objet. 

En plus, cette règle n’a pas toujours été suivie par le passé et certains doublons se sont vue attribué deux fiches, une pour le spécimen à MT, l’autre pour le spécimens provenant d’une autre institution.

Il faudrait allouer une fiche pour chaque objet physique et pouvoir identifier clairement les informations associées aux prêts.

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2012-03-01 15:30Z]

The management has been a headache since the beginning. Let's have a small meeting to discuss it once more.

**Comment by herbier** [comment]
[Originally posted on GoogleCode on 2012-03-01 18:06Z by amy.vandal.13]

Luc a proposé de faire une fiche par objet ce qui règlerait en grande partie le problème. 

Un meeting serait quand même important ne serait-ce que pour s'assurer que cette solution règle les différents cas de problèmes dans la table management. Je suis dispo n'importe quand.

**Comment by herbier** [comment]
[Originally posted on GoogleCode on 2012-03-22 19:40Z by amy.vandal.13]

Les directives quant à la création d'une fiche par objet ont été transmis aux utilisateurs de la base de données en attendants plus de détails. Cela rend la saisie de donnée plus simple mais il reste que la gestion des spécimens empruntés dans la base de donnée reste compliquée.

Il faudrait voir s'il est possible de passer par un autre moyen que celui d'utiliser la section «gestion» pour traiter des spécimens reliés aux emprunts, option que Stuart préconise et que je préfère aussi personnellement.

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2012-04-03 21:19Z]

As suggested on Monday, duplicates will be entered as separate records in the database. There is some work to do (maybe record as separate issue):
- Extend the atMT field: in collection, data only, unassigned, sent, unknown
- Create a sendFromMTTo field: with herbarium acronyms
- Create a sendFromMTDate field
- Create calculated "last repeated value" field from specimen history. Name as "receivedFromCalcul"
- Update the help buttons
- Explain to the staff/volunteers

- Extract the data from the management table
- Import appropriate records into database
- Remove management table

**Comment by herbier** [comment]
[Originally posted on GoogleCode on 2012-04-23 21:30Z by amy.vandal.13]

Le problème de la gestion difficile de l'information concernant les doublons et les spécimen n'appartenant pas à MT a été réglé par la suppression de la table Management. Voir l'Issue 138 pour les détails.
