### ISSUE TITLE
Carex specimens in envelope?

### ISSUE THREAD

**Issue by peterdesmet** [irbv-collections/MT-data#95]
[Originally posted on GoogleCode (id 155) on 2012-04-17]

<b>(This is the template to report a data issue. For another issue, change the</b>
<b>template above.)</b>

<b>What data issue did you discover in the database?</b>
Six Carex specimens have &quot;envelope&quot; as preparationType. I was wondering if this is an error or if they are actually stored in envelopes.

168646
168663
168711
172972
172973
172974

**Comment by herbier** [comment]
[Originally posted on GoogleCode on 2012-04-20 15:17Z by amy.vandal.13]

Geoff a vérifié les Carex mentionnés ci-haut, c'était tous des erreurs, le type de préparation a été changé pour "mounted"
