### ISSUE TITLE
Nom erroné

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-data#96]
[Originally posted on GoogleCode (id 50) on 2012-02-21 by cl.bouchard6]

<b>(This is the template to report a data issue. For another issue, change the</b>
<b>template above.)</b>

<b>What data issue did you discover in the database?</b>

ID 15927, 175914, 176008

Le choix Oxalis strica apparaît avant Oxalis stricta. Trois erreurs sont trouvées. Il faudra faire la correction du nom pour ces 3 entrées.

Claire Bouchard

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-03-07 21:09Z]

entrée corrigé - le nom n'est plus dans la bd
